#! /bin/sh

# Wallpaper
feh --bg-center /home/ifthenelse/picture/wallpaper/actual.jpg

# Keybidings
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# bspc config focus_follows_pointer true
bspc config border_width         4
bspc config active_border_color "#1b1a1b"
bspc config normal_border_color "#1b1a1b"
bspc config focused_border_color "#B01E19"
bspc config urgent_border_color "#B01E19"
bspc config presel_border_color "#1b1a1b"
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer false
bspc config history_aware_focus true
bspc config focus_by_distance true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
